### ISSUE TITLE
Crashes on edge Rails

### ISSUE THREAD

**Issue by ghiculescu** [basecamp/console1984#111]
Since https://github.com/rails/rails/pull/51760, apps using `console1984` won't boot, because this line raises:

https://github.com/basecamp/console1984/blob/215874e74daac9865ff09bf128be13b81b230c4f/lib/console1984/supervisor.rb#L1

I think that line is necessary, but I'm not sure how it works. If you comment it out, the test suite fails:

```
/Users/alex/code/console1984/lib/console1984/freezeable.rb:27:in `included': undefined method `thread_mattr_accessor' for Console1984::InputOutput:Module (NoMethodError)

    base.thread_mattr_accessor :prevent_instance_data_manipulation_after_freezing, default: true
        ^^^^^^^^^^^^^^^^^^^^^^
	from /Users/alex/code/console1984/lib/console1984/input_output.rb:2:in `include'
	from /Users/alex/code/console1984/lib/console1984/input_output.rb:2:in `<module:InputOutput>'
	from /Users/alex/code/console1984/lib/console1984/input_output.rb:1:in `<top (required)>'
	from /Users/alex/.rvm/gems/ruby-3.2.2/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:30:in `require'
	from /Users/alex/.rvm/gems/ruby-3.2.2/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:30:in `require'
	from /Users/alex/code/console1984/lib/console1984/supervisor.rb:4:in `<class:Supervisor>'
	from /Users/alex/code/console1984/lib/console1984/supervisor.rb:3:in `<top (required)>'
	from /Users/alex/.rvm/gems/ruby-3.2.2/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:30:in `require'
	from /Users/alex/.rvm/gems/ruby-3.2.2/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:30:in `require'
	from /Users/alex/code/console1984/lib/console1984.rb:43:in `<module:Console1984>'
	from /Users/alex/code/console1984/lib/console1984.rb:40:in `<top (required)>'
```

@st0012 are you able to advise?

**Comment by rosa** [comment]
Thanks @ghiculescu, and sorry for the delay! I've added https://github.com/basecamp/console1984/pull/113 while we fix the app to extend the Rails console through `Rails::ConsoleMethods`.  I think this should unblock upgrades to Rails Edge.

**Comment by rosa** [comment]
This one should be fixed now.

**Comment by rosa** [comment]
And improved with https://github.com/basecamp/console1984/pull/115.

**Comment by ghiculescu** [comment]
Thanks @rosa!
