### ISSUE TITLE
Can't start a console session

### ISSUE THREAD

**Issue by jeromedalbert** [basecamp/console1984#46]
When starting a console session in my development environment, I get the following error:

```
Unnamed, why are you using this console today?
testing
Traceback (most recent call last):
        42: from -e:1:in `<main>'
        41: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        40: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        39: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-7.0.2.3/lib/active_support/fork_tracker.rb:18:in `fork'
        38: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-7.0.2.3/lib/active_support/fork_tracker.rb:18:in `fork'
        37: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-7.0.2.3/lib/active_support/fork_tracker.rb:20:in `block in fork'
        36: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
        35: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
        34: from /Users/jerome/c/my_app/my_app/bin/rails:9:in `<main>'
        33: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        32: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        31: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        30: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        29: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        28: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        27: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/commands.rb:18:in `<main>'
        26: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/command.rb:48:in `invoke'
        25: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/command/base.rb:87:in `perform'
        24: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        23: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        22: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        21: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/commands/console/console_command.rb:102:in `perform'
        20: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/commands/console/console_command.rb:19:in `start'
        19: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/commands/console/console_command.rb:19:in `new'
        18: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/commands/console/console_command.rb:35:in `initialize'
        17: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/engine.rb:449:in `load_console'
        16: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/application.rb:525:in `run_console_blocks'
        15: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/engine/railties.rb:15:in `each'
        14: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/engine/railties.rb:15:in `each'
        13: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/application.rb:525:in `block in run_console_blocks'
        12: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/railtie.rb:267:in `run_console_blocks'
        11: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/railtie.rb:292:in `each_registered_block'
        10: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/railtie.rb:292:in `each'
         9: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.2.3/lib/rails/railtie.rb:267:in `block in run_console_blocks'
         8: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/console1984-0.1.22/lib/console1984/engine.rb:24:in `block in <class:Engine>'
         7: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/console1984-0.1.22/lib/console1984/supervisor.rb:25:in `start'
         6: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/console1984-0.1.22/lib/console1984/supervisor.rb:57:in `start_session'
         5: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/console1984-0.1.22/lib/console1984/sessions_logger/database.rb:8:in `start_session'
         4: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/console1984-0.1.22/lib/console1984/sessions_logger/database.rb:55:in `silence_logging'
         3: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-7.0.2.3/lib/active_support/logger_silence.rb:18:in `silence'
         2: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-7.0.2.3/lib/active_support/logger_thread_safe_level.rb:43:in `log_at'
         1: from /Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-7.0.2.3/lib/active_support/logger_silence.rb:18:in `block in silence'
/Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/console1984-0.1.22/lib/console1984/sessions_logger/database.rb:56:in `block in silence_logging': undefined method `silence' for #<Logger:0x00007f9b4367e590> (NoMethodError)
```

FYI my logger config is

```ruby
logger           = ActiveSupport::Logger.new(STDOUT)
logger.formatter = config.log_formatter
config.logger    = ActiveSupport::TaggedLogging.new(logger)
```

but it seems to be ignored as `Console1984::Base` is set to a a basic `Logger`, and I cannot find why. Looking at the gem's source code it seems that `Console1984::Base` is getting its logger from `ApplicationRecord` and ultimately `ActiveRecord::Base`, unless I am wrong.

I can sort of work around the issue by doing the following hack in an initializer:

```ruby
ActiveSupport.on_load(:console_1984_base) do
  Console1984::Base.logger = ActiveRecord::Base.logger
end
```

But I don't think that is recommended, and when I do this my commands generate logs that aren't silenced (but maybe that is a separate problem):

```
irb(main):001:0> 1+1
D, [2022-03-30T16:39:24.098179 #28421] DEBUG -- :   Console1984::Command Count (2.0ms)  SELECT COUNT(*) FROM "console1984_commands" WHERE "console1984_commands"."session_id" = 10 /*application:MyApp,line:/Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/irb.rb:540:in `block (2 levels) in eval_input'*/
D, [2022-03-30T16:39:24.143082 #28421] DEBUG -- :   TRANSACTION (0.4ms)  BEGIN /*application:MyApp,line:/Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/irb.rb:540:in `block (2 levels) in eval_input'*/
D, [2022-03-30T16:39:24.144492 #28421] DEBUG -- :   Console1984::Command Create (1.1ms)  INSERT INTO "console1984_commands" ("statements", "session_id", "created_at", "updated_at") VALUES ('{"p":"N8tbIg==","h":{"iv":"cmbLlXNgsAOPnxXB","at":"dhqC9V1LpbCF3KM91bNplw=="}}', 10, '2022-03-30 23:39:24.139532', '2022-03-30 23:39:24.139532') RETURNING "id" /*application:MyApp,line:/Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/irb.rb:540:in `block (2 levels) in eval_input'*/
D, [2022-03-30T16:39:24.146245 #28421] DEBUG -- :   TRANSACTION (0.7ms)  COMMIT /*application:MyApp,line:/Users/jerome/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/irb.rb:540:in `block (2 levels) in eval_input'*/
2
irb(main):002:0>
```

Thank you for making this cool gem!

**Comment by jorgemanrubia** [comment]
Hi @jeromedalbert,

Oh interesting. Good troubleshooting there. As you say, `Console1984::Base.logger` should be `ActiveRecord::Base`'s, I am puzzled about why you have to do that explicitly. I imagine you are not tweaking your `ApplicationRecord`'s logger in your app, do you?

In that initializer, if you do:

```ruby
Console1984::Base.logger = ApplicationRecord.logger
```

That would narrow down the problem to something changing your `ApplicationRecord` logger.

I can't reproduce the problem myself. Can you reproduce in a fresh app with the same Rails version you are using?  Also, could you give a try to version 0.1.22 to see if the problem reproduces (last week I released a new version, to discard it's not related to those changes).

Let's see if we can figure this out. Thanks for the report.

**Comment by jeromedalbert** [comment]
I could not repro the issue on a fresh app either, so it had to be coming from my app. I should have done this before posting the issue, sorry about that! After some investigation I found the culprit:

```
# lib/my_app/database/clean_backup.rb
module MyApp
  module Database
    class CleanBackup
      ActiveRecord::Base.logger = Logger.new($stdout)

     ...
```

Ooops! Removing that line from the class evaluation and moving it to a more appropriate place fixed the issue.

Thank you for the detailed pointers.

**Comment by jorgemanrubia** [comment]
Hey no problem at all @jeromedalbert. Thanks for the follow up.
