### ISSUE TITLE
Incompatibility with the google-api-client gem

### ISSUE THREAD

**Issue by jeromedalbert** [basecamp/console1984#49]
It seems that there is some incompatibility between this gem and the `google-api-client` gem.

I hesitated between posting here or in the [googleapis/google-api-ruby-client](https://github.com/googleapis/google-api-ruby-client) repo, please let me know if I should post there instead.

## Error message

When starting a console session in my development environment, I get the following error:

```
~/c/tmp/my_app $ CONSOLE_USER=jerome rails c
/Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/uber-0.1.0/lib/uber/inheritable_attr.rb:12:in `map': uninitialized constant #<Class:Representable::Decorator>::InheritableAttribute (NameError)

          @map = InheritableAttribute.inherit_for(self, :map, {})
                 ^^^^^^^^^^^^^^^^^^^^
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/representable-3.1.1/lib/representable/cached.rb:9:in `block in build_definition'
        from <internal:kernel>:90:in `tap'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/representable-3.1.1/lib/representable/cached.rb:6:in `build_definition'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/declarative-0.0.20/lib/declarative/schema.rb:25:in `property'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/google-apis-core-0.4.2/lib/google/apis/core/json_representation.rb:100:in `property'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/google-api-client-0.53.0/generated/google/apis/webmasters_v3/representations.rb:88:in `<class:Representation>'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/google-api-client-0.53.0/generated/google/apis/webmasters_v3/representations.rb:87:in `<class:ApiDataRow>'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/google-api-client-0.53.0/generated/google/apis/webmasters_v3/representations.rb:85:in `<module:WebmastersV3>'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/google-api-client-0.53.0/generated/google/apis/webmasters_v3/representations.rb:23:in `<module:Apis>'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/google-api-client-0.53.0/generated/google/apis/webmasters_v3/representations.rb:22:in `<module:Google>'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/google-api-client-0.53.0/generated/google/apis/webmasters_v3/representations.rb:21:in `<main>'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/google-api-client-0.53.0/generated/google/apis/webmasters_v3.rb:17:in `<main>'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /Users/jerome/c/tmp/my_app/app/models/foo.rb:1:in `<main>'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/console1984-0.1.24/lib/console1984/ext/core/object.rb:34:in `const_get'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/console1984-0.1.24/lib/console1984/ext/core/object.rb:34:in `const_get'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:237:in `block (2 levels) in eager_load'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/autoloaders.rb:32:in `each'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/application.rb:497:in `eager_load!'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/console1984-0.1.24/lib/console1984/refrigerator.rb:15:in `eager_load_all_classes'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/console1984-0.1.24/lib/console1984/refrigerator.rb:6:in `freeze_all'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/console1984-0.1.24/lib/console1984/shield.rb:24:in `install'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/console1984-0.1.24/lib/console1984/supervisor.rb:15:in `install'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/console1984-0.1.24/lib/console1984/engine.rb:23:in `block in <class:Engine>'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/railtie.rb:267:in `block in run_console_blocks'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/railtie.rb:292:in `each'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/railtie.rb:292:in `each_registered_block'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/railtie.rb:267:in `run_console_blocks'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/application.rb:525:in `block in run_console_blocks'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/engine/railties.rb:15:in `each'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/engine/railties.rb:15:in `each'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/application.rb:525:in `run_console_blocks'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/engine.rb:449:in `load_console'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/commands/console/console_command.rb:35:in `initialize'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/commands/console/console_command.rb:19:in `new'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/commands/console/console_command.rb:19:in `start'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/commands/console/console_command.rb:102:in `perform'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/command/base.rb:87:in `perform'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/command.rb:48:in `invoke'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.2.3/lib/rails/commands.rb:18:in `<main>'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/jerome/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from bin/rails:4:in `<main>'
```

## Steps to repro

1. Make a new Rails 7 app
1. Install the `console1984` gem
1. Use the following in `application.rb`:

    ```ruby
    config.console1984.protected_environments = %i(development staging production)
    ```

1. Add `gem 'google-api-client'` in your gemfile and run `bundle install`
1. Create the following file:

    ```ruby
    # app/models/foo.rb
    require 'google/apis/webmasters_v3'

    class Foo
    end
    ```

1. Run `CONSOLE_USER=your_name rails c`
1. The error message I mentioned appears

## Other notes

- The issue also happens if you skip step 5, launch the rails console successfully, and type `require 'google/apis/webmasters_v3'`
- `require 'google/apis/webmasters_v3'` works fine if console1984 is not installed

**Comment by jorgemanrubia** [comment]
Hi @jeromedalbert. First, sorry for the super long delay here 🙏.

You can fix the problem by moving the `require` to `application.rb`  or to an initializer (a file in `config/initializers`). The problem here is that `console1984` freezes a lot of stuff when the console starts, and it seems that this library relies on some meta programming that is incompatible with this. By placing it in an initializer, it will make sure it runs before the freezing happens.
